# Standard parameters for equalization among libraries
# main key is the case name

cancer:
  random_state: 42


mnist:
  # overkill, these are standard, maybe they should be obtained from the dataset
  img_width: 28
  img_height: 28

  layer1_out: 512

  learning_rate: 0.001
  epochs: 5
  batch_size: 128

  random_state: 42


lstm:
  ticker: AAPL
  date_start: '2020-01-01'
  date_end: '2026-01-01'

  seq_length: 30

  input_dim: 1
  hidden_dim: 32
  num_layers: 2
  output_dim: 1

  learning_rate: 0.01
  epochs: 200

  # TODO
  random_state: 42


cnn:
  num_workers: 2
  batch_size: 32
  random_state: 42

  # TODO: connect to model
  ly_conv1_out: 12
  ly_conv1_kernel: 5
  ly_pool_kernel: 2
  ly_conv2_out: 24
  ly_conv2_kernel: 5
  ly_fc1_out: 120
  ly_fc2_out: 84

  learning_rate: 0.001
  momentum: 0.9
  epochs: 30
  model_file: "data/trained/cnn_cifar10.pth"

