# Standard parameters for equalization among libraries
# main key is the case name

cancer:
  random_state: 42


mnist:
  # imposed by the dataset
  img_width: 28
  img_height: 28

  random_state: 42
  batch_size: 128
  learning_rate: 0.001
  epochs: 5

  ly_fc1_out: 512


lstm:
  ticker: AAPL
  date_start: '2020-01-01'
  date_end: '2026-01-01'

  random_state: 42  # TODO
  seq_length: 30
  learning_rate: 0.01
  epochs: 200

  input_dim: 1
  hidden_dim: 32
  num_layers: 2
  output_dim: 1


cnn:
  train_loop: False  #train and save, or load weights from file
  model_file: "data/trained/cnn_cifar10.pth"

  # imposed by the dataset
  img_width: 32
  img_height: 32

  random_state: 42
  num_workers: 2
  batch_size: 32
  learning_rate: 0.001
  momentum: 0.9
  epochs: 30

  # TODO: connect to model
  ly_conv1_out: 12
  ly_conv1_kernel: 5
  ly_pool_kernel: 2
  ly_conv2_out: 24
  ly_conv2_kernel: 5
  ly_fc1_out: 120
  ly_fc2_out: 84


llm:
  random_state: 42

  # TODO: standarize book -> repo names
  data_url: "https://www.thelmbook.com/data/news"
  emb_dim: 128
  num_heads: 8
  num_blocks: 2
  batch_size: 131072 #65536 #131072 (8589934592 bytes) #128
  learning_rate: 0.001 #0.001
  num_epochs: 1
  context_size: 30
